language: fr
word: application
type: nom féminin
etymology: latin applicatio
definitions:
  - Action d'appliquer quelque chose, de poser, d'étendre une chose sur une autre pour qu'elle y adhère.
  - 'Action d''employer quelque chose à une fin déterminée ou de le mettre en pratique : Les applications d''une nouvelle technique.'
  - 'Qualité de quelqu''un qui apporte soin et attention à ce qu''il fait : Élève travaillant avec application.'
  - (Bourse) 1.  Technique qui permet aux actionnaires d'une société cotée de vendre à d'autres leurs titres ou une partie d'entre eux en bloc, par l'intermédiaire d'une société de Bourse, en assurant la publicité du prix auquel s'effectue la transaction.2.  Partie des transactions qui se compensent chez un même intermédiaire en Bourse et qui n'influencent pas les cours.
  - (Broderie) Élément rapporté se distinguant du fond par la matière, la technique ou la couleur.
  - (Céramique) Procédé de décoration consistant à poser la couleur vitrifiable sous la couverte à la façon d'un engobe.
  - (Couture) Motif décoratif en tissu, en cuir, etc., fixé sur un vêtement par des points au ras du bord.
  - (Informatique) 1.  Domaine délimité pour le traitement duquel est écrit un programme.2.  Programme ou ensemble de programmes destiné à aider l'utilisateur d'un ordinateur pour le traitement d'une tâche précise.
  - (Mathématiques) Opération qui fait correspondre à tout élément x d'un ensemble A (ensemble de départ ou de définition) un élément y et un seul d'un ensemble B (ensemble d'arrivée). [y est l'image de x ; x est un antécédent de y. On distingue les applications injectives, surjectives et bijectives.]
  - (Peintures et vernis) Action de déposer sur un subjectile une peinture, un vernis ou une préparation assimilée.
synonyms: []
