language: fr
word: autoroutes
type: nom féminin
etymology: calque de l'italien autostrada
definitions:
  - Voie exclusivement réservée à la circulation des véhicules automobiles, ne comportant qu'un nombre limité d'accès, établis de façon à éviter tout cisaillement et ne présentant aucun croisement à niveau.
synonyms: []
