language: fr
word: automation
type: nom féminin
etymology: mot anglais
definitions:
  - Vieilli. Mode d'organisation d'un ensemble de procédés ou de systèmes visant à rendre automatique une suite d'opérations.
synonyms: []
