language: fr
word: choucroutes
type: nom féminin
etymology: alsacien surkrut, de l'allemand sauer, aigre, et Kraut, herbe
definitions:
  - Chou blanc haché, salé et fermenté.
  - Ce chou cuit dans de la graisse avec du vin blanc, des baies de genièvre et du porc, servi avec des pommes de terre bouillies.
synonyms: []
