language: fr
word: condamnaient
type: verbe transitif
etymology: latin condemnare, avec l'influence de damnare, infliger une peine
definitions:
  - 'Déclarer quelqu''un officiellement et en justice coupable d''un délit, d''un crime et lui infliger telle ou telle peine : On l''a condamné pour vol à cinq ans de prison.'
  - 'Déclarer qu''un acte est répréhensible, blâmable et que son auteur est passible d''une peine : La loi condamne le chantage.'
  - 'Déclarer un mot, une expression non conformes aux règles et aux usages d''une langue ; en désapprouver l''emploi : L''Académie condamne certains mots employés par les médias.'
  - 'Juger et déclarer quelqu''un ou quelque chose fautif, blâmable ou responsable d''un mal, prouver que quelque chose est faux, erroné, non adéquat ; critiquer, réprouver : L''opposition condamne la politique du gouvernement.'
  - 'Être l''élément qui prouve la culpabilité de quelqu''un, qui prouve que quelqu''un ou quelque chose est responsable d''un acte fautif, blâmable : Cette nouvelle preuve le condamnait irrémédiablement.'
  - 'Déclarer quelqu''un incurable, perdu : Tous le condamnaient et miraculeusement il a guéri.'
  - 'Déterminer la ruine, la mort d''un groupe, d''une activité, d''une entreprise : En fermant ces usines c''est la ville entière que vous condamnez.'
  - 'Obliger, astreindre quelqu''un, un groupe à agir de telle manière, à se trouver dans tel état : Sa maladie le condamne à l''inaction.'
  - 'Interdire l''usage d''un lieu, d''un accès en le fermant, le barrant, le murant, etc. : Condamner une porte, une fenêtre.'
synonyms: []
