language: fr
word: condamnation
type: nom féminin
etymology: latin condemnatio, -onis
definitions:
  - 'Action de condamner quelqu''un, quelque chose : Condamnation d''un voleur.'
  - 'Fait qui constitue un témoignage accablant contre quelqu''un, quelque chose, qui le condamne : Cet échec est la condamnation d''une politique.'
  - 'Fait qui détermine la ruine, la mort de quelque chose, quelqu''un : Ces mesures sont la condamnation des petites entreprises.'
  - Décision d'une juridiction prononçant une peine, une obligation ou une sanction.
  - Dispositif d'une serrure permettant d'interdire le fonctionnement du demi-tour.
synonyms: []
