language: fr
word: configurerait
type: verbe transitif
etymology: ""
definitions:
  - (Informatique) Régler les paramètres d’un logiciel ou d’un matériel pour le faire fonctionner dans des conditions données.
synonyms: []
