language: fr
word: configuration
type: nom féminin
etymology: latin ecclésiastique configuratio, -onis, de configurare, donner une forme
definitions:
  - 'Forme extérieure d''un ensemble ; relief : La configuration d''un pays.'
  - 'Aspect général de quelque chose d''abstrait, caractère d''ensemble, physionomie : Son nom a une configuration germanique.'
  - (Informatique) 1.  Ensemble des caractéristiques matérielles et logicielles d'un système informatique (processeur, mémoire, système d'exploitation…).2.  Modification ou réglage de paramètres informatiques en vue de l'optimisation du fonctionnement du système.
  - (Psychologie) Synonyme de forme.
synonyms: []
