language: fr
word: décomposeraient
type: verbe transitif
etymology: ""
definitions:
  - 'Réduire une substance en éléments plus simples ; faire apparaître, par analyse, les composantes d''un phénomène : Le prisme décompose la lumière.'
  - 'Diviser un tout en ses éléments simples, en extraire les parties constitutives pour l''expliquer, en analyser la structure : Décomposer un raisonnement.'
  - 'Faire un mouvement complexe très lentement pour faire ressortir chacune de ses étapes : Décomposer un pas de danse.'
  - 'Altérer profondément une matière et, en particulier, la putréfier : La chaleur décompose la viande.'
  - 'Rompre l''unité, l''organisation de quelque chose, corrompre, détruire : Selon lui, le relâchement moral décomposera cette société.'
  - 'En parlant d''une émotion forte, modifier profondément quelqu''un, l''expression de son visage ; altérer : La peur décomposa ses traits.'
synonyms: []
