language: fr
word: inapplication
type: nom féminin
etymology: ""
definitions:
  - 'Fait de ne pas avoir été appliqué : L''inapplication d''un système.'
  - Littéraire. Manque de soin, de sérieux, d'application dans ce qu'on fait.
synonyms: []
