language: fr
word: produit
type: nom masculin
etymology: ""
definitions:
  - 'Ce qui naît d''une activité de la nature ou de l''homme : Produits de la terre. Produit du travail.'
  - 'Ce qui résulte d''une activité, d''un état, d''une situation quelconque : Un pur produit de l''imagination.'
  - 'Bénéfices, fonds, sommes obtenues : Le produit de l''impôt.'
  - 'Production de l''industrie, de l''agriculture, des services, etc. : Produits pétroliers.'
  - 'Personne considérée comme fabriquée par un milieu, un groupe, une situation : Ces délinquants sont les produits de notre société.'
  - 'Chacun des articles, objets, biens, services proposés sur le marché par une entreprise : Consultez la liste de nos produits.'
  - 'Substance que l''on utilise pour l''entretien, les soins ou un usage particulier : Produit pour la vaisselle.'
  - (Chimie) Corps résultant d'une opération, d'une réaction.
  - "(Mathématiques) Pour deux éléments a et b de ℕ, ℤ, \U0001D53B, ℚ, ℝ ou ℂ, élément de ce même ensemble égal à l'image de (a, b) par l'opération de multiplication."
synonyms: []
