language: fr
word: productif
type: adjectif
etymology: latin productum, de producere, produire
definitions:
  - 'Qui rapporte de l''argent, qui est rentable : Un capital productif d''un fort intérêt.'
  - 'Qui fournit, produit quelque chose en quantité : Un sol peu productif.'
  - 'Dont la productivité est grande : Une entreprise productive.'
  - Se dit d'un acte juridique qui produit tel effet de droit.
synonyms: []
