language: fr
word: productions
type: nom féminin
etymology: de produire
definitions:
  - 'Action de produire, de faire exister ; fait de se produire : La production d''un son.'
  - Ensemble de moyens qui aboutissent à la création d'un bien nouveau ou d'un service.
  - 'Ce qui est produit par la nature, l''art, l''esprit : Les productions maraîchères. La dernière production d''un écrivain.'
  - 'Quantité de biens et de services produits au cours d''une période donnée ou au cours d''un cycle de fabrication : Accélérer sa production.'
  - 'Stade de l''économie où l''on produit ; ensemble des moyens mis en œuvre pour produire des biens de consommation : Les prix restent stables à la production.'
  - Action de produire un film, une émission de télévision ou de radio, etc. ; l'émission, le film eux-mêmes.
  - 'Action de montrer, d''exhiber, etc. : La production d''un acte de naissance.'
  - (Pétrole) Ensemble des techniques relatives à l'exploitation d'un gisement de pétrole.
synonyms: []
