language: fr
word: prodiges
type: nom masculin
etymology: latin prodigium
definitions:
  - Événement extraordinaire, de caractère magique ou surnaturel.
  - 'Acte extraordinaire, merveille : Ce médicament fait des prodiges.'
  - 'Personne exceptionnellement douée : Cet enfant est un petit prodige.'
synonyms: []
