language: fr
word: produite
type: verbe transitif
etymology: latin producere, avec l'influence de conduire
definitions:
  - 'Assurer les actions diverses (culture, fabrication, etc.) qui concourent à fournir sur le marché commercial certains biens ou services : Région qui produit du vin.'
  - 'Créer une œuvre, la composer : Écrivain qui produit plusieurs romans par an.'
  - 'Former naturellement quelque chose, donner : Arbre qui produit des fruits.'
  - 'Provoquer l''apparition de quelque chose, le créer, en être la source : Frottement qui produit de la chaleur.'
  - 'Faire naître un sentiment, une sensation, etc. : Cette révélation produisit un effet de stupéfaction.'
  - 'En parlant d''une collectivité, donner naissance à quelque chose, quelqu''un, les former : Pays qui a produit de nombreux prix Nobel.'
  - 'Montrer quelque chose, en faire état, amener quelqu''un devant quelqu''un d''autre : Pour se justifier, il m''a produit un certificat de maladie.'
  - Être le producteur d'un film, d'une émission, etc.
synonyms: []
