language: fr
word: productrices
type: nom masculin
etymology: ""
definitions:
  - Personne, pays, entreprise qui produit un bien économique.
  - Homme qui produit les substances alimentaires qui lui sont nécessaires (ou les fait produire par un autre). [La production, qui succède à la prédation, est le deuxième stade du développement économique des sociétés humaines.]
synonyms: []
