language: fr
word: prodigueriez
type: verbe transitif
etymology: latin prodigere
definitions:
  - Dépenser de l'argent sans compter.
  - 'Dépenser quelque chose ou l''accorder sans parcimonie, sans compter : Prodiguer son talent.'
  - 'Faire montre de quelque chose, l''accorder à quelqu''un d''une manière très démonstrative ou avec excès : Prodiguer des marques de sympathie à ses hôtes.'
synonyms: []
