language: fr
word: prodigieusement
type: adverbe
etymology: ""
definitions:
  - 'D''une manière prodigieuse : Il joue prodigieusement du violon.'
  - 'Au plus haut point, extrêmement : Un film prodigieusement ennuyeux.'
synonyms: []
