language: fr
word: prodigieux
type: adjectif
etymology: latin prodigiosus
definitions:
  - 'Littéraire. Qui tient du prodige, du miracle : Guérison prodigieuse.'
  - 'Qui est remarquable, extraordinaire, qui sort du commun : Avoir des connaissances prodigieuses.'
  - 'Indique le très haut degré : Une bêtise prodigieuse.'
synonyms: []
