language: fr
word: prodigalité
type: nom féminin
etymology: bas latin prodigalitas, -atis
definitions:
  - 'Caractère de quelqu''un de prodigue, propension à la dépense : Sa prodigalité finira par le ruiner.'
  - (Surtout pluriel) Acte qui révèle ce caractère.
  - 'Littéraire. Présence très importante, excessive de quelque chose : La prodigalité d''un ensemble baroque.'
synonyms: []
