language: fr
word: productivités
type: nom féminin
etymology: ""
definitions:
  - 'Caractère productif de quelque chose, d''une activité : Productivité d''un sol.'
  - Rapport entre le résultat d'une activité productive (biens et services) et les facteurs de production que l'on a utilisés pour parvenir à cette production. (On distingue communément la productivité du capital, rapport de la valeur ajoutée au capital fixe productif en volume, la productivité du travail, rapport de la valeur ajoutée au nombre d'heures travaillées, et la productivité globale des facteurs, qui rapporte la valeur ajoutée au volume des deux facteurs capital et travail.)
  - (Écologie) Masse de substance vivante produite, dans un temps donné, sur une surface terrestre ou dans un volume d'eau marine ou lacustre donnés.
synonyms: []
