language: fr
word: prodromes
type: nom masculin
etymology: latin prodromus, du grec prodromos, précurseur
definitions:
  - Symptôme de début d'une maladie, annonçant en particulier une crise aiguë.
  - 'Littéraire. Signe annonciateur marquant le début de quelque chose : Les prodromes d''une insurrection.'
synonyms: []
