language: fr
word: service
type: nom masculin
etymology: latin servitium, de servire, être esclave
definitions:
  - 'Ensemble des obligations que les citoyens ont envers l''État, la société ; travail déterminé effectué pour leur compte : Le service de l''État.'
  - Fonction de domestique dans une maison privée.
  - Célébration de l'office divin.
  - 'Travail de quelqu''un chargé de servir des clients dans un restaurant, un magasin, un hôtel : Service rapide, soigné.'
  - 'Ensemble des repas servis à des heures échelonnées dans une cantine, un wagon-restaurant : Aller au premier, au deuxième service.'
  - Ensemble des plats composant une partie du repas et qui étaient apportés en même temps.
  - 'Pourcentage d''une note d''hôtel, de restaurant, etc., spécialement affecté au personnel : 15 % de service.'
  - 'Activité professionnelle exercée dans une entreprise, une administration : Avoir quarante ans de service.'
  - En Afrique, lieu de travail, en particulier bureau.
  - 'Organisme qui fait partie d''un ensemble administratif ou économique ; organe d''une entreprise chargé d''une fonction précise, ensemble de personnes assurant cette fonction : Les services commerciaux d''une entreprise.'
  - 'Usage que l''on peut faire de quelque chose : Outil qui rend de grands services.'
  - 'Ce que l''on fait pour quelqu''un, avantage qu''on lui donne spontanément : Il m''est difficile de demander ce service à Paul.'
  - 'Liaison assurée par un moyen de transport collectif : Le service d''été de la S.N.C.F.'
  - 'Expédition, distribution d''une publication périodique : Le service des abonnements à un hebdomadaire.'
  - Action de servir au tennis, au tennis de table, au volley-ball, etc.
  - Ensemble des objets (vaisselle, verrerie, argenterie) ou des articles de linge pour la table ; assortiment de pièces destinées à un usage spécial (service à thé, à liqueurs, etc.).
  - (Électricité) Séquence de conditions de fonctionnement auxquelles est soumis un composant, un dispositif ou un équipement.
  - (Militaire) Nom donné aux grands corps destinés à satisfaire les besoins généraux (administration, matériels, ravitaillement, etc.) des armées (par opposition aux armes, chargées de mener le combat).
  - (Théâtre) Places gratuites réservées par un théâtre pour diverses catégories d'invités (service des artistes, service de presse).
  - (Zootechnie) Saillie d'un étalon, et, plus généralement, d'un reproducteur mâle quelconque.
synonyms: []
