language: fr
word: services
type: nom masculin pluriel
etymology: ""
definitions:
  - 'Ensemble des travaux effectués pour quelqu''un : Se passer des services d''un employé.'
  - En Suisse, synonyme de couverts.
  - Par opposition aux biens, avantages ou satisfactions fournis par les entreprises ou par l'État au public, à titre gratuit ou onéreux.
synonyms: []
