language: fr
word: site
type: nom masculin
etymology: italien sito, du latin situs
definitions:
  - 'Paysage considéré du point de vue de son pittoresque : Un site classé.'
  - 'Configuration d''un lieu au regard d''une destination précise ; ce lieu : Site de lancement.'
  - (Économie) Lieu où est implantée une activité industrielle ou commerciale.
  - (Génétique) La plus petite sous-unité, à l'intérieur d'un gène, capable de mutation et de recombinaison. (Cette sous-unité est la paire de bases de la molécule d'A.D.N.)
  - (Géographie) Configuration propre du lieu occupé par une ville, et qui lui fournit les éléments locaux de vie matérielle et les possibilités d'extension (ravitaillement en eau, nature du sol, etc.).
  - (Informatique) Ensemble de pages Web accessibles via Internet sur un serveur identifié par une adresse.
synonyms: []
