language: fr
word: trains
type: nom masculin
etymology: de traîner
definitions:
  - Convoi de chemin de fer en ordre de marche constitué par un ou plusieurs engins moteurs (locomotives, automotrices, etc.), remorquant ou non un ou plusieurs véhicules ; moyen de transport ferroviaire.
  - 'Ensemble de véhicules avançant à la suite, remorqués ou motorisés, et constituant une unité de transport : Un train de péniches.'
  - 'Ensemble de dispositions législatives ou administratives concernant un même objet : Un train de mesures économiques.'
  - 'Allure plus ou moins rapide de quelqu''un, d''une bête de trait, d''un véhicule : Accélérer le train.'
  - 'Cours, enchaînement des faits, succession d''événements : Être pris dans le train de la vie quotidienne.'
  - (Chemin de fer) Synonyme de convoi.
  - (Mécanique) Ensemble d'organes semblables accouplés pour permettre un résultat déterminé.
  - (Militaire) Arme chargée de la circulation et des transports routiers dans l'armée de terre.
  - (Turf) Vitesse plus ou moins grande à laquelle est courue une épreuve.
synonyms: []
