language: fr
word: training
type: nom masculin
etymology: anglais training, entraînement
definitions:
  - Vieux. Entraînement sportif.
  - Chaussure de sport, possédant généralement une tige basse de textile ou de cuir et une semelle cuvette en caoutchouc.
  - Synonyme de survêtement.
synonyms: []
