language: fr
word: traintrain
type: nom masculin invariable (Réf. ortho. nom masculin)
etymology: moyen français trantran, son du cor, avec l'influence de train
definitions:
  - 'Familier. Marche régulière et monotone des occupations habituelles : Le train-train familial.'
synonyms: []
